<a href="https://colab.research.google.com/github/viknesh20-20/Data-Science-Tasks/blob/main/Task_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# library functios used for data science
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/iris.csv")# used to read csv file
df.head()#used to display the head of the data frame

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
a = np.array([1,2,3,4]) #useed to create an array
a

array([1, 2, 3, 4])

In [ ]:
a=np.ones((2,2))#used to create an array of ones
a

array([[1., 1.],
       [1., 1.]])

In [ ]:
a=np.zeros((2,2)) #used to create an array of zeros
a

array([[0., 0.],
       [0., 0.]])

In [ ]:
a=np.arange(1,100,3) #Arrange the values within the limit with step value
a

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [ ]:
a= np.linspace(1,20,10) #Arrange the values within the limit with point value
a

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [ ]:
A=np.eye(3,3) #creates an identity matrix
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A.shape # gives the shape of the array

(3, 3)

In [ ]:
A.ndim #returnss the dimension of the array

2

In [ ]:
A.size #returns the size of the array

9

In [ ]:
A.dtype #returns the datatype of the array

dtype('float64')

In [ ]:
B=np.add(A,5) #add two arrays or value
B

array([[6., 5., 5.],
       [5., 6., 5.],
       [5., 5., 6.]])

In [ ]:
B=np.subtract(A,5) #sub two values or array
B

array([[-4., -5., -5.],
       [-5., -4., -5.],
       [-5., -5., -4.]])

In [ ]:
B=np.multiply(B,-1) #multiply two values or with the value
B

array([[4., 5., 5.],
       [5., 4., 5.],
       [5., 5., 4.]])

In [ ]:
B=np.divide(B,5) #divide the values of arrary or value
B

array([[0.8, 1. , 1. ],
       [1. , 0.8, 1. ],
       [1. , 1. , 0.8]])

In [ ]:
C=np.dot(A,B) #performs a dot product
C

array([[0.8, 1. , 1. ],
       [1. , 0.8, 1. ],
       [1. , 1. , 0.8]])

In [ ]:
C = C.reshape(9,1) #change the shape of the array
C

array([[0.8],
       [1. ],
       [1. ],
       [1. ],
       [0.8],
       [1. ],
       [1. ],
       [1. ],
       [0.8]])

In [ ]:
A= np.array([1,2,3])
C = np.array([4,5,6])
D=np.concatenate((A,C),axis=0) #concatenates two array

In [ ]:
D=np.split(D,2)
D      #split a array into sub arrays

[array([1, 2, 3]), array([4, 5, 6])]

In [ ]:

C = np.array([[4,5,6],[7,8,9]])
C=np.transpose(C)  #transpose of a array
C

array([[4, 7],
       [5, 8],
       [6, 9]])

In [ ]:
A=np.array([1,2,3,4,5,6,7]) #performs the sum of the elements in a array
np.sum(A)

28

In [ ]:
np.mean(A) #finds the mean of an array

4.0

In [ ]:
np.median(A) #finds the median of the array

4.0

In [ ]:
np.std(A) #finds the standard deviation of the array

2.0

In [ ]:
np.min(A) # finds the minimum of the array

1

In [ ]:
np.max(A) #finds the maximum of the array

7

#Trignometric functions

In [ ]:
np.sin(A)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ])

In [ ]:
np.cos(A)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225])

In [ ]:
np.tan(A)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798])

In [ ]:
np.arcsin(A)

<ipython-input-31-eff75137e39f>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(A)


array([1.57079633,        nan,        nan,        nan,        nan,
              nan,        nan])

In [ ]:
np.arccos(A)

<ipython-input-32-517610c9be1d>:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(A)


array([ 0., nan, nan, nan, nan, nan, nan])

In [ ]:
np.arctan(A)

array([0.78539816, 1.10714872, 1.24904577, 1.32581766, 1.37340077,
       1.40564765, 1.42889927])

#Random functions

In [ ]:
Z= np.random.rand(2,2)
Z

array([[0.23298856, 0.71795133],
       [0.17357145, 0.90982685]])

In [ ]:
Z=np.random.randn(2,2)
Z

array([[ 0.33463423, -0.2256648 ],
       [-0.17386591, -0.96697552]])

In [ ]:
Z=np.random.randint(1,4)
Z

1

In [ ]:
np.random.shuffle([1,2,3])